name: Release Action

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Create Release
              id: release
              uses: caffeine-soft/github-release-tag@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  generate_release: "true"
                  release_name: "Release {tag}"

            - name: Update Major Tag
              run: |
                  MAJOR_VERSION=$(echo "${{ steps.release.outputs.new_tag }}" | cut -d. -f1)
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git tag -fa "$MAJOR_VERSION" -m "Update major tag $MAJOR_VERSION"
                  git push origin "$MAJOR_VERSION" --force
